import Head from 'next/head'
export default function Home() {
	return (
		<>
			<Head>
				<title>LUXICON</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/icon.svg" />
			</Head>
			<main className='w-full bg-yellow-300'>LuxIcon</main>
		</>
	)
}
